theme: jekyll-theme-slate

plugins:
  - jekyll-seo-tag

title: MTCaptcha Recaptcha Fallback Sample Code

description: Sample javascript code to fallback on to MTCaptcha if reCaptcha fail to load in China or other reasons.
